// Utility function to shuffle arrays
export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

export interface Video {
  id: number
  title: string
  channel: string
  views: string
  time: string
  thumbnail: string
  duration: string
  channelAvatar: string | null
  description?: string
}

export interface Bit {
  id: number
  title: string
  channel: string
  views: string
  time: string
  video: string
  likes: number
  dislikes: number
  comments: number
  channelAvatar: string | null
}

export interface Post {
  id: number
  title: string
  content: string
  author: string
  authorAvatar: string | null
  image?: string // Only images or GIFs allowed, no videos
  likes: number
  dislikes: number
  comments: number
  shares: number
  time: string
  views?: number
}

export const VIDEO_FILES = {
  UHD_4096_1: '/video/7644958-uhd_4096_2160_24fps.mp4',
  UHD_4096_2: '/video/4488717-uhd_4096_2160_25fps.mp4',
  UHD_3840_1: '/video/3120322-uhd_3840_2160_24fps.mp4',
  UHD_3840_2: '/video/4912725-uhd_3840_2160_24fps.mp4',
  UHD_3840_3: '/video/14938708_3840_2160_25fps.mp4',
  HD_1: '/video/1536315-hd_1920_1080_30fps.mp4',
  HD_2: '/video/2022395-hd_1920_1080_30fps.mp4',
  HD_3: '/video/2928284-hd_1920_1080_30fps.mp4',
  HD_4: '/video/3460025-hd_1920_1080_24fps.mp4',
  HD_5: '/video/3603859-hd_1920_1080_25fps.mp4',
  HD_6: '/video/854429-hd_1920_1080_24fps.mp4',
}

export const IMAGE_FILES = {
  IMG_1: '/image/pexels-alteredsnaps-14600321.jpg',
  IMG_2: '/image/pexels-freestockpro-1031780.jpg',
  IMG_3: '/image/pexels-freestockpro-1929611.jpg',
  IMG_4: '/image/pexels-georgesultan-1471803.jpg',
  IMG_5: '/image/pexels-igor-starkov-233202-3470076.jpg',
  IMG_6: '/image/pexels-igor-starkov-233202-3806244.jpg',
  IMG_7: '/image/pexels-jakeheinemann-2380784.jpg',
  IMG_8: '/image/pexels-jerome031-2114365.jpg',
  IMG_9: '/image/pexels-koolshooters-8531229.jpg',
  IMG_10: '/image/pexels-ktfoto-1271380.jpg',
  IMG_11: '/image/pexels-lukas-rodriguez-1845331-3680219.jpg',
  IMG_12: '/image/pexels-lukas-rodriguez-1845331-4967858.jpg',
  IMG_13: '/image/pexels-marleneleppanen-1426620.jpg',
  IMG_14: '/image/pexels-maumascaro-801863.jpg',
  IMG_15: '/image/pexels-mediocrememories-2240763.jpg',
  IMG_16: '/image/pexels-nextvoyage-3030647.jpg',
  IMG_17: '/image/pexels-nout-gons-80280-378570.jpg',
  IMG_18: '/image/pexels-olly-787961.jpg',
  IMG_19: '/image/pexels-owenbarker-1118341.jpg',
  IMG_20: '/image/pexels-peng-liu-45946-169647.jpg',
  IMG_21: '/image/pexels-pixabay-161154.jpg',
  IMG_22: '/image/pexels-pixabay-209207.jpg',
  IMG_23: '/image/pexels-pixabay-219692.jpg',
  IMG_24: '/image/pexels-pixabay-358229.jpg',
  IMG_25: '/image/pexels-quentin-martinez-2147503099-30685277.jpg',
  IMG_26: '/image/pexels-skyriusmarketing-2129796.jpg',
  IMG_27: '/image/pexels-tomverdoot-1571882.jpg',
  IMG_28: '/image/pexels-vikramstudio46-1119796.jpg',
  IMG_29: '/image/pexels-vishnurnair-1105666 (1).jpg',
  IMG_30: '/image/pexels-vishnurnair-1105666.jpg',
  IMG_31: '/image/pexels-vladalex94-1461378.jpg',
  IMG_32: '/image/pexels-vladalex94-1486222.jpg',
  IMG_33: '/image/pexels-vovaflame-2770516.jpg',
  IMG_34: '/image/pexels-w-w-299285-889839.jpg',
  IMG_35: '/image/pexels-wendywei-1190298.jpg',
  IMG_36: '/image/pexels-wesleydavi-3622619.jpg',
  IMG_37: '/image/pexels-yaroslav-shuraev-7689143.jpg',
  IMG_38: '/image/pexels-zaksheuskaya-709412-1616403.jpg',
  IMG_39: '/image/aleksandr-popov-9vDdkxSCAD4-unsplash.jpg',
  IMG_40: '/image/aleksandr-popov-hTv8aaPziOQ-unsplash.jpg',
  IMG_41: '/image/alex-azabache--Hm_xIcYbUY-unsplash.jpg',
  IMG_42: '/image/anthony-delanoix-hzgs56Ze49s-unsplash.jpg',
  IMG_43: '/image/danny-howe-bn-D2bCvpik-unsplash.jpg',
  IMG_44: '/image/hardini-lestari-N3TypD-awJQ-unsplash.jpg',
  IMG_45: '/image/igor-starkov-Cx-MtcVHR2c-unsplash.jpg',
  IMG_46: '/image/jacob-bentzinger-_HXFz-0g9w8-unsplash.jpg',
  IMG_47: '/image/junior-moran-08yuHdEW6Lc-unsplash.jpg',
  IMG_48: '/image/karl-hedin-wN3q1ANmXJQ-unsplash.jpg',
  IMG_49: '/image/pablo-heimplatz-ZODcBkEohk8-unsplash.jpg',
  
}

export const VIDEOS: Video[] = [
  {
    id: 1,
    title: 'The Future of Streaming - 8K 60fps Experience',
    channel: 'Lambrk Official',
    views: '1.2M views',
    time: '2 days ago',
    thumbnail: VIDEO_FILES.UHD_4096_1,
    duration: '12:34',
    channelAvatar: null,
    description: 'Experience the future of streaming with ultra-high definition 8K resolution at 60 frames per second. Discover how cutting-edge technology delivers an unparalleled viewing experience with crystal-clear visuals and smooth motion.',
  },
  {
    id: 2,
    title: 'Dolby Vision & Atmos - Premium Audio Visual Experience',
    channel: 'Lambrk Tech',
    views: '856K views',
    time: '5 days ago',
    thumbnail: VIDEO_FILES.UHD_3840_1,
    duration: '8:45',
    channelAvatar: null,
    description: 'Immerse yourself in the ultimate audio-visual experience with Dolby Vision HDR and Dolby Atmos surround sound. Learn how these technologies transform your viewing experience.',
  },
  {
    id: 3,
    title: 'AI-Powered Recommendations Explained',
    channel: 'Lambrk AI',
    views: '432K views',
    time: '1 week ago',
    thumbnail: VIDEO_FILES.UHD_4096_2,
    duration: '15:22',
    channelAvatar: null,
    description: 'Discover how artificial intelligence powers our recommendation system to help you find content you will love.',
  },
  {
    id: 4,
    title: 'Multi-Device Streaming Setup Guide',
    channel: 'Lambrk Official',
    views: '234K views',
    time: '2 weeks ago',
    thumbnail: VIDEO_FILES.HD_2,
    duration: '6:18',
    channelAvatar: null,
    description: 'Learn how to seamlessly stream across all your devices with our comprehensive setup guide.',
  },
  {
    id: 5,
    title: 'RAW Quality Streaming - What You Need to Know',
    channel: 'Lambrk Tech',
    views: '189K views',
    time: '3 weeks ago',
    thumbnail: VIDEO_FILES.UHD_3840_2,
    duration: '10:55',
    channelAvatar: null,
    description: 'Understand RAW quality streaming and how it delivers the most authentic viewing experience possible.',
  },
  {
    id: 6,
    title: 'HDR Support and Color Accuracy',
    channel: 'Lambrk Official',
    views: '156K views',
    time: '1 month ago',
    thumbnail: VIDEO_FILES.HD_3,
    duration: '9:30',
    channelAvatar: null,
    description: 'Explore High Dynamic Range (HDR) technology and its impact on color accuracy and visual fidelity.',
  },
  {
    id: 7,
    title: 'Fast Streaming Technology Deep Dive',
    channel: 'Lambrk Tech',
    views: '98K views',
    time: '1 month ago',
    thumbnail: VIDEO_FILES.HD_4,
    duration: '14:12',
    channelAvatar: null,
    description: 'Dive deep into our fast streaming technology and learn how we minimize buffering and maximize quality.',
  },
  {
    id: 8,
    title: 'Getting Started with Lambrk Platform',
    channel: 'Lambrk Official',
    views: '67K views',
    time: '2 months ago',
    thumbnail: VIDEO_FILES.HD_5,
    duration: '7:45',
    channelAvatar: null,
    description: 'A comprehensive guide to getting started with the Lambrk streaming platform.',
  },
]

export const BITS: Bit[] = [
  {
    id: 1,
    title: 'Quick Tech Tip: Keyboard Shortcuts',
    channel: 'TechTips',
    views: '2.3M',
    time: '3 hours ago',
    video: VIDEO_FILES.HD_1,
    likes: 125000,
    dislikes: 3200,
    comments: 3200,
    channelAvatar: null,
  },
  {
    id: 2,
    title: 'Amazing Nature Moment',
    channel: 'NatureLovers',
    views: '5.1M',
    time: '1 day ago',
    video: VIDEO_FILES.UHD_4096_1,
    likes: 890000,
    dislikes: 12000,
    comments: 12000,
    channelAvatar: null,
  },
  {
    id: 3,
    title: 'Cooking Hack You Need to Know',
    channel: 'ChefDaily',
    views: '1.8M',
    time: '2 days ago',
    video: VIDEO_FILES.HD_6,
    likes: 45000,
    dislikes: 2100,
    comments: 2100,
    channelAvatar: null,
  },
  {
    id: 4,
    title: 'Workout Motivation',
    channel: 'FitnessPro',
    views: '3.7M',
    time: '4 days ago',
    video: VIDEO_FILES.HD_2,
    likes: 234000,
    dislikes: 5600,
    comments: 5600,
    channelAvatar: null,
  },
  {
    id: 5,
    title: 'Funny Pet Moments',
    channel: 'PetVideos',
    views: '6.2M',
    time: '1 week ago',
    video: VIDEO_FILES.UHD_3840_3,
    likes: 567000,
    dislikes: 8900,
    comments: 8900,
    channelAvatar: null,
  },
]

export const POSTS: Post[] = [
  {
    id: 1,
    title: 'New Feature Announcement',
    content: 'We are excited to announce our new streaming features! Experience 8K quality streaming with enhanced audio support. This update brings significant improvements to video quality, playback performance, and user experience.\n\nKey features include:\n• 8K video resolution support\n• Enhanced audio quality with Dolby Atmos\n• Improved buffering and loading times\n• Better mobile experience\n• Advanced playback controls\n\nWe have been working hard to bring you these improvements, and we hope you enjoy the enhanced streaming experience. Your feedback is always welcome!',
    author: 'Lambrk Official',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_1,
    likes: 5420,
    dislikes: 120,
    comments: 234,
    shares: 89,
    time: '5 hours ago',
    views: 125000,
  },
  {
    id: 2,
    title: 'Community Update',
    content: 'Thank you to all our amazing users! We have reached 1 million active users this month. Your support means everything to us. We are committed to bringing you the best streaming experience possible.\n\nThis milestone would not have been possible without our incredible community. We are grateful for your continued support and feedback.\n\nAs we continue to grow, we remain focused on:\n• Improving platform performance\n• Adding new features based on your requests\n• Maintaining the highest quality standards\n• Building a vibrant and engaged community',
    author: 'Lambrk Team',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_2,
    likes: 12300,
    dislikes: 45,
    comments: 567,
    shares: 234,
    time: '1 day ago',
    views: 450000,
  },
  {
    id: 3,
    title: 'Tech Tips: Optimize Your Streaming',
    content: 'Want better streaming quality? Make sure you have a stable internet connection and close unnecessary background apps. Here are 5 tips to improve your experience:\n\n1) Use a wired connection when possible - Ethernet connections are more stable than WiFi\n2) Close other bandwidth-heavy applications - Streaming services, downloads, and cloud syncs can compete for bandwidth\n3) Update your browser or app regularly - New versions often include performance improvements\n4) Clear cache periodically - This can help resolve playback issues\n5) Check your internet speed - Make sure you have sufficient bandwidth for your desired quality\n\nFollowing these tips should significantly improve your streaming experience!',
    author: 'Lambrk Tech',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_3,
    likes: 8900,
    dislikes: 89,
    comments: 345,
    shares: 156,
    time: '2 days ago',
    views: 320000,
  },
  {
    id: 4,
    title: 'Behind the Scenes',
    content: 'Take a look at how we build the future of streaming. Our team works tirelessly to bring you the best experience possible. From our engineers to our designers, everyone is dedicated to making Lambrk the premier streaming platform.\n\nOur development process involves:\n• Continuous testing and optimization\n• User feedback integration\n• Regular feature updates\n• Performance monitoring\n• Security enhancements\n\nWe are always working behind the scenes to ensure you have the best possible experience.',
    author: 'Lambrk Official',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_4,
    likes: 6700,
    dislikes: 156,
    comments: 189,
    shares: 78,
    time: '3 days ago',
    views: 280000,
  },
  {
    id: 5,
    title: 'Platform Updates',
    content: 'We have been working on several improvements to enhance your viewing experience. New features include improved search functionality, better recommendations, and enhanced video player controls.',
    author: 'Lambrk Tech',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_5,
    likes: 4500,
    dislikes: 78,
    comments: 234,
    shares: 112,
    time: '4 days ago',
    views: 195000,
  },
  {
    id: 6,
    title: 'Welcome to Lambrk',
    content: 'Lambrk is your destination for high-quality streaming content. Whether you are looking for entertainment, education, or inspiration, we have something for everyone. Join our growing community today!',
    author: 'Lambrk Official',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_6,
    likes: 3200,
    dislikes: 45,
    comments: 156,
    shares: 67,
    time: '1 week ago',
    views: 150000,
  },
  {
    id: 7,
    title: 'Creative Content Showcase',
    content: 'Discover amazing content from our talented creators. From stunning visuals to inspiring stories, our platform is home to some of the most creative minds in the industry. Explore new perspectives and get inspired!',
    author: 'Lambrk Creative',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_7,
    likes: 8900,
    dislikes: 120,
    comments: 456,
    shares: 189,
    time: '1 week ago',
    views: 180000,
  },
  {
    id: 8,
    title: 'Mobile App Now Available',
    content: 'Great news! Our mobile app is now available on iOS and Android. Take your favorite content with you wherever you go. The app features offline downloads, personalized recommendations, and a seamless viewing experience.',
    author: 'Lambrk Team',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_8,
    likes: 11200,
    dislikes: 89,
    comments: 678,
    shares: 234,
    time: '1 week ago',
    views: 220000,
  },
  {
    id: 9,
    title: 'Summer Content Collection',
    content: 'Check out our curated summer collection featuring the best content for the season. From travel adventures to outdoor activities, we have something to keep you entertained all summer long.',
    author: 'Lambrk Curators',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_9,
    likes: 7600,
    dislikes: 156,
    comments: 345,
    shares: 167,
    time: '2 weeks ago',
    views: 195000,
  },
  {
    id: 10,
    title: 'Quality Matters: Our Commitment',
    content: 'At Lambrk, quality is not just a feature - it is our commitment. We continuously invest in technology and infrastructure to ensure you get the best possible viewing experience. Every video is optimized for maximum quality and performance.',
    author: 'Lambrk Official',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_10,
    likes: 5400,
    dislikes: 78,
    comments: 234,
    shares: 123,
    time: '2 weeks ago',
    views: 165000,
  },
  {
    id: 11,
    title: 'New Creator Program Launch',
    content: 'We are excited to launch our new creator program! Join thousands of content creators who are already sharing their stories on Lambrk. Get access to exclusive tools, analytics, and monetization options.',
    author: 'Lambrk Creators',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_11,
    likes: 9800,
    dislikes: 145,
    comments: 567,
    shares: 289,
    time: '2 weeks ago',
    views: 245000,
  },
  {
    id: 12,
    title: 'Privacy and Security First',
    content: 'Your privacy and security are our top priorities. We use industry-leading encryption and security measures to protect your data. Learn more about our privacy policy and how we keep your information safe.',
    author: 'Lambrk Security',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_12,
    likes: 6700,
    dislikes: 89,
    comments: 312,
    shares: 145,
    time: '3 weeks ago',
    views: 178000,
  },
  {
    id: 13,
    title: 'Global Expansion Announcement',
    content: 'Lambrk is now available in 50+ countries! We are expanding our global reach to bring high-quality streaming to more users worldwide. Thank you for being part of our journey.',
    author: 'Lambrk Global',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_13,
    likes: 12300,
    dislikes: 234,
    comments: 789,
    shares: 456,
    time: '3 weeks ago',
    views: 320000,
  },
  {
    id: 14,
    title: 'Accessibility Features Update',
    content: 'We have added new accessibility features to make our platform more inclusive. These include closed captions, audio descriptions, keyboard navigation, and screen reader support. Everyone deserves great content.',
    author: 'Lambrk Team',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_14,
    likes: 5600,
    dislikes: 67,
    comments: 234,
    shares: 112,
    time: '3 weeks ago',
    views: 145000,
  },
  {
    id: 15,
    title: 'Weekend Watchlist',
    content: 'Looking for something to watch this weekend? Check out our curated watchlist featuring the best new releases, trending content, and hidden gems. Perfect for a relaxing weekend binge session.',
    author: 'Lambrk Editors',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_15,
    likes: 8900,
    dislikes: 123,
    comments: 456,
    shares: 234,
    time: '4 weeks ago',
    views: 210000,
  },
  {
    id: 16,
    title: 'Live Streaming Now Available',
    content: 'Introducing live streaming! Now you can broadcast live events, Q&A sessions, and real-time content to your audience. Connect with your viewers in real-time and create engaging live experiences.',
    author: 'Lambrk Live',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_16,
    likes: 15200,
    dislikes: 189,
    comments: 890,
    shares: 567,
    time: '1 month ago',
    views: 380000,
  },
  {
    id: 17,
    title: 'Community Guidelines Update',
    content: 'We have updated our community guidelines to ensure a safe and positive environment for everyone. These guidelines help maintain a respectful community where all users can enjoy great content.',
    author: 'Lambrk Moderation',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_17,
    likes: 4200,
    dislikes: 89,
    comments: 234,
    shares: 98,
    time: '1 month ago',
    views: 135000,
  },
  {
    id: 18,
    title: 'Premium Subscription Benefits',
    content: 'Upgrade to Premium and unlock exclusive features including ad-free viewing, offline downloads, early access to new content, and priority customer support. Start your free trial today!',
    author: 'Lambrk Premium',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_18,
    likes: 11200,
    dislikes: 234,
    comments: 678,
    shares: 345,
    time: '1 month ago',
    views: 275000,
  },
  {
    id: 19,
    title: 'Content Discovery Made Easy',
    content: 'Our new recommendation engine uses advanced AI to help you discover content you will love. Based on your viewing history and preferences, we curate personalized recommendations just for you.',
    author: 'Lambrk AI',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_19,
    likes: 7800,
    dislikes: 145,
    comments: 456,
    shares: 234,
    time: '1 month ago',
    views: 195000,
  },
  {
    id: 20,
    title: 'Thank You for 2 Million Users',
    content: 'We are thrilled to announce that Lambrk has reached 2 million active users! This incredible milestone would not have been possible without your support. Thank you for being part of our community.',
    author: 'Lambrk Official',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_20,
    likes: 18900,
    dislikes: 234,
    comments: 1234,
    shares: 678,
    time: '1 month ago',
    views: 450000,
  },
  {
    id: 21,
    title: 'Photography Masterclass Series',
    content: 'Join us for an exclusive photography masterclass series featuring world-renowned photographers. Learn advanced techniques, composition rules, and post-processing tips to elevate your photography skills. Whether you are a beginner or professional, there is something for everyone in this comprehensive series.',
    author: 'Lambrk Creative',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_39,
    likes: 12400,
    dislikes: 156,
    comments: 789,
    shares: 345,
    time: '3 days ago',
    views: 285000,
  },
  {
    id: 22,
    title: 'Nature Photography Expedition',
    content: 'Embark on a virtual journey through stunning natural landscapes captured by our talented photographers. From majestic mountains to serene lakes, experience the beauty of nature through breathtaking imagery. These collections showcase the diversity and wonder of our natural world.',
    author: 'Lambrk Nature',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_40,
    likes: 15600,
    dislikes: 189,
    comments: 923,
    shares: 456,
    time: '4 days ago',
    views: 320000,
  },
  {
    id: 23,
    title: 'Urban Photography Showcase',
    content: 'Explore the vibrant energy of city life through our urban photography collection. From bustling streets to architectural marvels, discover the unique character of cities around the world. These images capture the essence of urban living and modern architecture.',
    author: 'Lambrk Urban',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_41,
    likes: 9800,
    dislikes: 123,
    comments: 567,
    shares: 234,
    time: '5 days ago',
    views: 245000,
  },
  {
    id: 24,
    title: 'Portrait Photography Techniques',
    content: 'Master the art of portrait photography with our comprehensive guide. Learn about lighting, posing, composition, and how to capture the personality of your subjects. Perfect for photographers looking to improve their portrait skills and create stunning images.',
    author: 'Lambrk Photography',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_42,
    likes: 11200,
    dislikes: 145,
    comments: 678,
    shares: 289,
    time: '6 days ago',
    views: 265000,
  },
  {
    id: 25,
    title: 'Travel Photography Adventures',
    content: 'Follow our photographers as they document incredible journeys around the globe. From remote destinations to popular tourist spots, these travel photography collections inspire wanderlust and showcase the beauty of different cultures and landscapes.',
    author: 'Lambrk Travel',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_43,
    likes: 18900,
    dislikes: 234,
    comments: 1234,
    shares: 567,
    time: '1 week ago',
    views: 380000,
  },
  {
    id: 26,
    title: 'Minimalist Photography Collection',
    content: 'Discover the beauty of simplicity through our minimalist photography collection. These images prove that less is more, focusing on clean compositions, negative space, and essential elements. Perfect for those who appreciate elegant and refined visual aesthetics.',
    author: 'Lambrk Minimal',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_44,
    likes: 8700,
    dislikes: 98,
    comments: 456,
    shares: 198,
    time: '1 week ago',
    views: 195000,
  },
  {
    id: 27,
    title: 'Architectural Photography Excellence',
    content: 'Explore stunning architectural photography that showcases both modern and historic buildings. From skyscrapers to ancient structures, these images highlight the artistry and engineering behind architectural design. A must-see for architecture enthusiasts.',
    author: 'Lambrk Architecture',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_45,
    likes: 13400,
    dislikes: 167,
    comments: 789,
    shares: 345,
    time: '1 week ago',
    views: 295000,
  },
  {
    id: 28,
    title: 'Landscape Photography Masterpieces',
    content: 'Immerse yourself in breathtaking landscape photography featuring mountains, valleys, coastlines, and more. These masterpieces capture the grandeur and beauty of natural landscapes, inspiring appreciation for the world around us. Perfect for nature lovers and photography enthusiasts.',
    author: 'Lambrk Landscapes',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_46,
    likes: 16700,
    dislikes: 201,
    comments: 1023,
    shares: 489,
    time: '2 weeks ago',
    views: 345000,
  },
  {
    id: 29,
    title: 'Street Photography Stories',
    content: 'Experience the raw and authentic moments of everyday life through our street photography collection. These images capture candid moments, emotions, and the human experience in urban environments. Each photograph tells a unique story of life in the city.',
    author: 'Lambrk Street',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_47,
    likes: 10900,
    dislikes: 134,
    comments: 623,
    shares: 267,
    time: '2 weeks ago',
    views: 255000,
  },
  {
    id: 30,
    title: 'Wildlife Photography Expedition',
    content: 'Get up close with nature through our wildlife photography collection. These stunning images showcase animals in their natural habitats, capturing their behavior, beauty, and the delicate balance of ecosystems. A celebration of biodiversity and conservation.',
    author: 'Lambrk Wildlife',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_48,
    likes: 19800,
    dislikes: 245,
    comments: 1456,
    shares: 678,
    time: '2 weeks ago',
    views: 420000,
  },
  {
    id: 31,
    title: 'Abstract Photography Gallery',
    content: 'Explore the world of abstract photography where colors, shapes, and textures take center stage. These artistic images challenge perception and invite viewers to see the world from a different perspective. Perfect for those who appreciate creative and experimental photography.',
    author: 'Lambrk Abstract',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_49,
    likes: 9200,
    dislikes: 112,
    comments: 512,
    shares: 223,
    time: '2 weeks ago',
    views: 210000,
  },
]

export const TRENDING_VIDEOS: Video[] = [
  {
    id: 1,
    title: 'Breaking: New Technology Revolution',
    channel: 'TechNews',
    views: '15.2M views',
    time: '2 hours ago',
    thumbnail: VIDEO_FILES.UHD_4096_1,
    duration: '8:45',
    channelAvatar: null,
  },
  {
    id: 2,
    title: 'Viral Dance Challenge Takes Over',
    channel: 'DanceCentral',
    views: '12.8M views',
    time: '5 hours ago',
    thumbnail: VIDEO_FILES.UHD_3840_1,
    duration: '3:22',
    channelAvatar: null,
  },
  {
    id: 3,
    title: 'Amazing Science Experiment Goes Viral',
    channel: 'ScienceLab',
    views: '9.5M views',
    time: '1 day ago',
    thumbnail: VIDEO_FILES.UHD_4096_2,
    duration: '6:15',
    channelAvatar: null,
  },
  {
    id: 4,
    title: 'Epic Fail Compilation 2024',
    channel: 'FunnyVids',
    views: '8.3M views',
    time: '1 day ago',
    thumbnail: VIDEO_FILES.HD_2,
    duration: '10:30',
    channelAvatar: null,
  },
  {
    id: 5,
    title: 'Cooking Hack That Changed Everything',
    channel: 'ChefMaster',
    views: '7.1M views',
    time: '2 days ago',
    thumbnail: VIDEO_FILES.UHD_3840_2,
    duration: '4:50',
    channelAvatar: null,
  },
  {
    id: 6,
    title: 'Top 10 Moments of the Year',
    channel: 'TopLists',
    views: '6.4M views',
    time: '2 days ago',
    thumbnail: VIDEO_FILES.HD_3,
    duration: '12:18',
    channelAvatar: null,
  },
]

export const TRENDING_BITS: Bit[] = [
  {
    id: 1,
    title: 'Quick Life Hack Everyone Needs',
    channel: 'LifeHacks',
    views: '18.5M',
    time: '1 hour ago',
    video: VIDEO_FILES.HD_4,
    likes: 2100000,
    dislikes: 45000,
    comments: 125000,
    channelAvatar: null,
  },
  {
    id: 2,
    title: 'Mind-Blowing Magic Trick',
    channel: 'MagicShow',
    views: '15.2M',
    time: '3 hours ago',
    video: VIDEO_FILES.HD_5,
    likes: 1800000,
    dislikes: 32000,
    comments: 98000,
    channelAvatar: null,
  },
  {
    id: 3,
    title: 'Pet Doing Something Adorable',
    channel: 'PetVideos',
    views: '12.8M',
    time: '6 hours ago',
    video: VIDEO_FILES.HD_6,
    likes: 1500000,
    dislikes: 28000,
    comments: 87000,
    channelAvatar: null,
  },
]

export const TRENDING_POSTS: Post[] = [
  {
    id: 1,
    title: 'Major Platform Update Announcement',
    content: 'We are thrilled to announce our biggest update yet! This includes new features, improved performance, and enhanced user experience. Join us as we continue to innovate and improve.',
    author: 'Lambrk Official',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_21,
    likes: 45000,
    dislikes: 890,
    comments: 5600,
    shares: 2300,
    time: '4 hours ago',
    views: 520000,
  },
  {
    id: 2,
    title: 'Community Milestone Reached',
    content: 'Thank you to our amazing community! We have reached 5 million active users. Your support and engagement make this platform what it is today.',
    author: 'Lambrk Team',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_22,
    likes: 38000,
    dislikes: 650,
    comments: 4200,
    shares: 1800,
    time: '8 hours ago',
    views: 480000,
  },
  {
    id: 3,
    title: 'New Feature Spotlight',
    content: 'Check out our latest feature that makes content creation easier than ever. We have been working hard to bring you the best tools for your creative journey.',
    author: 'Lambrk Tech',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_23,
    likes: 29000,
    dislikes: 520,
    comments: 3100,
    shares: 1400,
    time: '1 day ago',
    views: 360000,
  },
  {
    id: 4,
    title: 'Viral Content Alert',
    content: 'This week we have seen some incredible viral content on our platform. From heartwarming stories to hilarious moments, our community never fails to amaze us. Check out the trending section!',
    author: 'Lambrk Trending',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_24,
    likes: 34000,
    dislikes: 456,
    comments: 2890,
    shares: 1678,
    time: '1 day ago',
    views: 420000,
  },
  {
    id: 5,
    title: 'Creator Spotlight: Featured Artist',
    content: 'Meet this month featured creator! Their unique content and creative vision have inspired thousands. Discover their work and get inspired to create your own amazing content.',
    author: 'Lambrk Creators',
    authorAvatar: null,
    image: IMAGE_FILES.IMG_25,
    likes: 25600,
    dislikes: 345,
    comments: 1890,
    shares: 1234,
    time: '2 days ago',
    views: 310000,
  },
]

